// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Data;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    [Migration("20230320014902_removeusertable")]
    partial class removeusertable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TodoApp.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Description = "Eat Ice Cream",
                            DueDate = new DateTime(2023, 3, 20, 17, 49, 2, 260, DateTimeKind.Local).AddTicks(9309),
                            Status = false,
                            Title = "Buy Ice Cream"
                        },
                        new
                        {
                            Id = 5,
                            Description = "In Jump training",
                            DueDate = new DateTime(2023, 3, 22, 9, 49, 2, 260, DateTimeKind.Local).AddTicks(9329),
                            Status = false,
                            Title = "Learn Data Seeding"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Entity Customization",
                            DueDate = new DateTime(2023, 3, 21, 9, 49, 2, 260, DateTimeKind.Local).AddTicks(9331),
                            Status = false,
                            Title = "Learn Fluent Api"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
